title: 'RStudio Server'
connection: 'connection.html.mustache'
compute:
  - name: 'RStudio Server'
    batch: 'owens'
    node:
      - type: 'any'
        ppn: 28
        desc: >
          Choose any type of compute node. This reduces the wait time
          as there are no node specific requirements.
    webserver?: true
    pbs:
      envvars:
        R_MODULE: 'R/3.3.2'
        RSTUDIO_MODULE: 'rstudio/1.0.136_server'
        PROOT_PATH: '/usr/local/bin/proot'
